#!/usr/bin/env bash
set -e
set -u
set -o pipefail

if [[ $# -ne 1 ]]; then
  echo 'must pass exactly 1 argument' 1>&2
  exit 1
fi


# find current script directory
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# if symlinked, resolve to real path
if [[ -L "${BASH_SOURCE[0]}" ]]; then
  real_path="$(readlink "${BASH_SOURCE[0]}")"
  script_dir="$(cd "$(dirname "$real_path")" && pwd)"
fi

path="$script_dir/../snippets/$1"

die() {
  echo "no snippet found at $path" 1>&2
  exit 1
}

cat "$path" 2>/dev/null || die